### ISSUE TITLE
repository name should be aniprasad.github.io not aniprasad.github.com

### ISSUE THREAD

**Issue by xgupta** [aniprasad/aniprasad.github.com#1]

**Comment by aniprasad** [comment]
Apologies for "ignoring" this. 

This is a personal website. The advantage of hosting it here, is I can just buy the domain name, and not have to pay for hosting charges :)  I'd rather keep it as .com now, since my links elsewhere point to it.

I appreciate the eagle eye in spotting something that could be changed, but its a personal website. If you're interested in collaborating on other patches/issues, I'll be more than happy to add you on LLVM patches that I put up (since I do see that you're contributing quite a bit there :)
